name: NSLS-II-MIDAS
channels:
  - defaults
  - conda-forge
dependencies:
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.0=h19a0ad4_0
  - bottleneck=1.3.2=py39h7cc1a96_1
  - brotli=1.0.9=ha925a31_2
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.7.5=haa95532_1
  - cached-property=1.5.2=py_0
  - certifi=2021.5.30=py39haa95532_0
  - cfitsio=3.470=he774522_6
  - charls=2.2.0=h6c2663c_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cycler=0.10.0=py39haa95532_0
  - cytoolz=0.11.0=py39h2bbff1b_0
  - dask-core=2021.6.2=pyhd3eb1b0_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - fsspec=2021.6.0=pyhd3eb1b0_0
  - giflib=5.2.1=h62dcd97_0
  - h5py=3.2.1=py39h3de5c98_0
  - hdf5=1.10.6=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - imagecodecs=2021.6.8=py39h5da4933_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - intel-openmp=2021.2.0=haa95532_616
  - ipython=7.22.0=py39hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py39haa95532_1
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.3.1=py39hd77b12b_0
  - lcms2=2.12=h83e58a3_0
  - lerc=2.2.1=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libdeflate=1.7=h2bbff1b_5
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - libzopfli=1.0.3=ha925a31_0
  - locket=0.2.1=py39haa95532_1
  - lz4-c=1.9.3=h2bbff1b_0
  - matplotlib-base=3.3.4=py39h49ac443_0
  - mkl=2021.2.0=haa95532_296
  - mkl-service=2.3.0=py39h2bbff1b_1
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.1=py39hf11a4ad_2
  - networkx=2.5=py_0
  - numexpr=2.7.3=py39hb80d3ca_1
  - numpy=1.20.2=py39ha4e8547_0
  - numpy-base=1.20.2=py39hc2deb75_0
  - olefile=0.46=py_0
  - openjpeg=2.3.0=h5ec785f_1
  - openssl=1.1.1k=h2bbff1b_0
  - pandas=1.2.5=py39hd77b12b_0
  - parso=0.7.0=py_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py39h4fa10fc_0
  - pip=21.1.3=py39haa95532_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyqtgraph=0.11.0=py_0
  - pyreadline=2.1=py39haa95532_1
  - pystackreg=0.2.5=py39h2e25243_0
  - python=3.9.5=h6244533_3
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py39h080aedc_4
  - pyyaml=5.4.1=py39h2bbff1b_1
  - qt=5.9.7=vc14h73c81de_0
  - scikit-image=0.18.1=py39hf11a4ad_0
  - scikit-learn=0.24.2=py39hf11a4ad_1
  - scipy=1.6.2=py39h66253e8_1
  - setuptools=52.0.0=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=h33f27b4_0
  - sqlite=3.36.0=h2bbff1b_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2021.4.8=pyhd3eb1b0_2
  - tk=8.6.10=he774522_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2021a=h52ac0ba_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py39h2bbff1b_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zfp=0.5.5=hd77b12b_6
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - asteval==0.9.25
    - atomicwrites==1.4.0
    - attrs==21.2.0
    - chardet==4.0.0
    - fabio==0.11.0
    - future==0.18.2
    - greenlet==1.1.0
    - idna==2.10
    - iniconfig==1.1.1
    - lmfit==1.0.2
    - packaging==21.0
    - peakutils==1.3.3
    - pluggy==0.13.1
    - py==1.10.0
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyshortcuts==1.8.0
    - pytest==6.2.4
    - pywin32==301
    - requests==2.25.1
    - silx==0.15.2
    - sqlalchemy==1.4.20
    - termcolor==1.1.0
    - toml==0.10.2
    - uncertainties==3.1.5
    - urllib3==1.26.6
    - xraydb==4.4.7
    - xraylarch==0.9.51


